# Generated by Django 6.0.4 on 2026-07-25 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['region', 'name'],
                'unique_together': {('name', 'region')},
            },
        ),
    ]
