# Generated by Django 6.0.4 on 2026-08-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_youthprofile_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('jhs', 'JHS'), ('shs', 'SHS'), ('shs_graduate', 'SHS Graduate'), ('tertiary', 'Tertiary'), ('dropout_re_entry', 'Dropout Re-entry'), ('teen_mother_program', 'Teen Mother Program')], max_length=30, null=True),
        ),
    ]
