# Generated by Django 6.0.4 on 2026-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
