# Generated by Django 6.0.4 on 2026-08-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_institution_application_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('university', 'University'), ('technical_university', 'Technical University'), ('college_of_education', 'College of Education'), ('nursing_training_college', 'Nursing Training College'), ('tvet_centre', 'TVET Centre')], max_length=30),
        ),
    ]
