/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#727a69',
        surface: '#fff8f6',
        'on-error': '#ffffff',
        'on-surface-variant': '#42493a',
        'on-primary-fixed-variant': '#285000',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0ed',
        'on-background': '#2b1611',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#fbffe4',
        'tertiary-container': '#647e00',
        'on-secondary-fixed-variant': '#364c3c',
        'surface-container': '#ffe9e4',
        'secondary-fixed-dim': '#b4cdb8',
        error: '#ba1a1a',
        'tertiary-fixed': '#ccf05f',
        'outline-variant': '#c2c9b6',
        'on-tertiary': '#ffffff',
        'surface-variant': '#ffdad2',
        'surface-container-high': '#ffe2db',
        'on-primary-fixed': '#0d2000',
        'inverse-primary': '#9cd769',
        'primary-container': '#4d821d',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary-container': '#f9ffec',
        'primary-fixed': '#b7f481',
        'on-secondary-container': '#516857',
        primary: '#366800',
        'surface-dim': '#f9d1c8',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#161e00',
        'on-surface': '#2b1611',
        'inverse-on-surface': '#ffede9',
        'surface-tint': '#386b01',
        'on-tertiary-fixed-variant': '#3c4d00',
        'inverse-surface': '#432a25',
        'on-secondary-fixed': '#0b2013',
        'surface-container-highest': '#ffdad2',
        'surface-bright': '#fff8f6',
        tertiary: '#4e6400',
        'primary-fixed-dim': '#9cd769',
        'secondary-container': '#cde6d1',
        background: '#fff8f6',
        'tertiary-fixed-dim': '#b1d446',
        'secondary-fixed': '#d0e9d4',
        secondary: '#4d6453',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        // 2xl/3xl are the standard card/surface and hero/feature-moment
        // radii respectively — explicit here so every page draws from the
        // same two tiers instead of drifting onto arbitrary values.
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        lg: '48px',
        md: '24px',
        xs: '4px',
        xl: '80px',
        gutter: '20px',
        'margin-mobile': '16px',
        sm: '12px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Work Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Work Sans"', 'sans-serif'],
        'label-sm': ['"Work Sans"', 'sans-serif'],
        'label-md': ['"Work Sans"', 'sans-serif'],
        'label-lg': ['"Work Sans"', 'sans-serif'],
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      // Shared motion vocabulary — every animated element in the app draws
      // from these instead of one-off durations/eases, so movement feels
      // consistent whether it's a page section, a modal, or a button press.
      transitionTimingFunction: {
        emphasized: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(100%)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.5s cubic-bezier(0.2, 0, 0, 1) both',
        'fade-in': 'fade-in 0.3s ease-out both',
        'scale-in': 'scale-in 0.2s cubic-bezier(0.2, 0, 0, 1) both',
        'slide-up': 'slide-up 0.3s cubic-bezier(0.2, 0, 0, 1) both',
      },
    },
  },
  plugins: [],
}
