# Generated by Django 6.0.4 on 2026-07-25 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('ngo', 'NGO'), ('helpline', 'Helpline'), ('school_counselor', 'School Counselor')], max_length=30, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'escalation_contacts',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('pregnancy', 'Pregnancy'), ('family_pressure', 'Family Pressure'), ('financial_hardship', 'Financial Hardship'), ('re_enrolment', 'Re-enrolment')], max_length=30, null=True)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('escalation_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to='helpcentre.escalationcontact')),
            ],
            options={
                'db_table': 'help_requests',
            },
        ),
    ]
