# Generated by Django 6.0.4 on 2026-07-25 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('earnings_range', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification_required', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'career_paths',
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='accounts.youthprofile')),
            ],
            options={
                'db_table': 'quiz_responses',
            },
        ),
        migrations.CreateModel(
            name='CareerMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='careers.careerpath')),
                ('quiz_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='careers.quizresponse')),
            ],
            options={
                'db_table': 'career_matches',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('career_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='careers.careerpath')),
            ],
            options={
                'db_table': 'scholarships',
            },
        ),
    ]
