# Generated by Django 6.0.4 on 2026-07-31 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_youthprofile_education_level'),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('youth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_conversation', to='accounts.youthprofile')),
            ],
            options={
                'db_table': 'counsellor_conversations',
            },
        ),
        migrations.CreateModel(
            name='CounsellorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='careers.counsellorconversation')),
            ],
            options={
                'db_table': 'counsellor_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
