# Generated by Django 6.0.4 on 2026-08-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_opportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careermatch',
            options={'verbose_name_plural': 'career matches'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['deadline', 'title'], 'verbose_name_plural': 'opportunities'},
        ),
    ]
