# Generated by Django 6.0.4 on 2026-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
        ('careers', '0004_alter_careermatch_options_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='career_paths', to='accounts.institution'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='trait',
            field=models.CharField(blank=True, choices=[('TECH', 'Technology & Computing'), ('PEOPLE', 'Healthcare, Education & Social Services'), ('CREATIVE', 'Arts, Media & Design'), ('BUSINESS', 'Business, Finance & Entrepreneurship'), ('PRACTICAL', 'Engineering, Construction & Agriculture')], max_length=20, null=True),
        ),
    ]
