# Generated by Django 6.0.4 on 2026-08-18 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_institution_type'),
        ('careers', '0005_careerpath_institutions_careerpath_trait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('day_to_day', models.TextField(blank=True, null=True)),
                ('typical_earnings', models.CharField(blank=True, max_length=100, null=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='careers.careerpath')),
            ],
            options={
                'db_table': 'career_roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('hnd', 'HND'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree")], default='bachelors', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_requirements', models.TextField(blank=True, null=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='careers.careerpath')),
                ('careers', models.ManyToManyField(blank=True, related_name='courses', to='careers.career')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.institution')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['title'],
            },
        ),
    ]
