# Generated by Django 6.0.4 on 2026-07-25 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to='accounts.counselorprofile')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='accounts.youthprofile')),
            ],
            options={
                'db_table': 'risk_assessments',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='risk.riskassessment')),
            ],
            options={
                'db_table': 'interventions',
            },
        ),
        migrations.CreateModel(
            name='RiskIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('academic_decline', 'Academic Decline'), ('absenteeism', 'Absenteeism'), ('financial_distress', 'Financial Distress'), ('behavioural_change', 'Behavioural Change')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='risk.riskassessment')),
            ],
            options={
                'db_table': 'risk_indicators',
            },
        ),
    ]
