# Generated by Django 6.0.4 on 2026-08-02 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_youthprofile_assigned_counselor'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='accounts.youthprofile')),
            ],
            options={
                'db_table': 'academic_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('academic_checkin', 'Academic Check-in'), ('home_visit', 'Home Visit'), ('mentorship_pairing', 'Mentorship Pairing'), ('crisis_support', 'Crisis Support'), ('other', 'Other')], max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='accounts.counselorprofile')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='accounts.youthprofile')),
            ],
            options={
                'db_table': 'counseling_sessions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.youthprofile')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date'],
                'unique_together': {('youth', 'date')},
            },
        ),
    ]
