# Generated by Django 6.0.4 on 2026-07-25 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('narrative', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('career_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='careers.careerpath')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'db_table': 'stories',
            },
        ),
    ]
