# Generated by Django 6.0.4 on 2026-07-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
