# Generated by Django 6.0.4 on 2026-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
